export const SET_USER = 'SET_USER'
export const LOGOUT = 'LOGOUT'
export const USER_EXIST = 'USER_EXIST'
export const LOGIN_USER = 'LOGIN_USER'
export const USER_NOT_FOUND = 'USER_NOT_FOUND '
export const TURNOFF_ERROR_AUTH = 'TURNOFF_ERROR_AUTH'
